/**
 * The marker shown next to a task that repeats.
 *
 * Recurrence was only visible inside the Recurring table and on the Calendar,
 * so a task looked one-off in the Assignment tables — you could not tell, while
 * editing a row, that it belongs to something that regenerates.
 *
 * "Recurring" means the same thing here as it does on the Calendar
 * (see isRecurring in lib/taskSchedule.ts): the task was generated BY a
 * recurring template. The template itself is not marked — it lives in the
 * Recurring table, and marking it would make one task read as recurring in the
 * Assignment table but one-off on the Calendar.
 *
 * Lives in its own file, like RevisionBadge, because it belongs anywhere a task
 * is listed.
 */
export default function RecurringBadge({
  fromTemplateId,
}: {
  /** assigned_tasks.recurring_template_id — set when spawned by a template. */
  fromTemplateId?: string | null;
}) {
  if (!fromTemplateId) return null;

  return (
    <span
      title="Repeats — generated from a recurring template"
      aria-label="Recurring"
      className="ml-1.5 inline-flex shrink-0 items-center rounded-sm bg-amber-soft px-[3px] font-bold text-amber"
    >
      ↻
    </span>
  );
}
